package model;
// Generated Jul 13, 2020 11:32:57 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="projectdb"
)
public class User  implements java.io.Serializable {


     private Integer id;
     private Person person;
     private String username;
     private String email;
     private String contact;
     private String subtype;
     private Date dos;
     private String password;

    public User() {
    }

	
    public User(Date dos) {
        this.dos = dos;
    }
    public User(Person person, String username, String email, String contact, String subtype, Date dos, String password) {
       this.person = person;
       this.username = username;
       this.email = email;
       this.contact = contact;
       this.subtype = subtype;
       this.dos = dos;
       this.password = password;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="UserID")
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }

    
    @Column(name="username", length=100)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="contact", length=100)
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }

    
    @Column(name="subtype", length=100)
    public String getSubtype() {
        return this.subtype;
    }
    
    public void setSubtype(String subtype) {
        this.subtype = subtype;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dos", nullable=false, length=19)
    public Date getDos() {
        return this.dos;
    }
    
    public void setDos(Date dos) {
        this.dos = dos;
    }

    
    @Column(name="password")
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


